### ISSUE TITLE
Feature request: option to disable timestamp generation

### ISSUE THREAD

**Issue by obiwanzenobi** [PlugFox/pubspec_generator#6]
Please give an option to disable timestamp generation. This causes some unwanted changes and git merge conflicts. 
Config could be in build.yaml.

```yaml
      pubspec_generator:
        options:
          generate_timestamp: false
          output: lib/gen/pubspec.yaml.g.dart
```
